### ISSUE TITLE
4cceditor has stopped working.

### ISSUE THREAD

**Issue by maprezentalok** [the4chancup/4ccEditor#1]
Hi there, I tried the latest release, for PES17 it works very well, but for PES19 (datapack 2.0) after clicking on the "Load 19 Edit file"  and selecting the EDIT00000000 file it immediately greys and the "4ccEditor.exe has stopped working" window pops up.

**Comment by Noteperson** [comment]
Please try the latest editor release and let me know if the problem persists.

**Comment by maprezentalok** [comment]
Sorry man, it was a false error even for pes17, if I remember correctly, I had not started the game before using the tool or something like that.
Anyway great to see pes21 is now supported, I don't have to hexedit the bitfields manually lol. Also great fan of 4chan pes cups with the funny models mwhahaha so keep up the good work. :D

**Comment by 7osman07** [comment]
i tried the latest version for pes18 and it has the same problem
