### ISSUE TITLE
team swap issue

### ISSUE THREAD

**Issue by w-tim** [the4chancup/4ccEditor#6]
Yesterday, I spent most of the day looking for an editor that can directly support editing PES2021 game saves. Yours was the fastest and most stable, and it successfully completed the editing. However, I would like to know if there is any way to support team swaps? For example, I really like the Shanghai Shenhua team from my hometown Shanghai, which is in the Chinese Super League. Is there a way to replace one of the teams in the Master League with a team from the English Premier League?

**Comment by Noteperson** [comment]
You should be able to achieve this by selecting the team you wish to move in the editor, saving it as a 4ccs file (using Team > Save Squad), then selecting the team you wish to overwrite, and importing the 4ccs file (Team > Load squad) over it.
